CREATE TYPE "IngredientType" AS ENUM ('INGREDIENT', 'EQUIPMENT', 'PACKAGING');
ALTER TABLE "Ingredient" ADD COLUMN IF NOT EXISTS "type" "IngredientType" NOT NULL DEFAULT 'INGREDIENT';
ALTER TABLE "Ingredient" ADD COLUMN IF NOT EXISTS "notes" TEXT;
